- name: functions
  hosts: local
  connection: local
  vars:
    technologies: Devops, Linux, Shell, Ansible
    tags:
      Application: payment
      Environment: dev
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Ramesh') }}"

  - name: convert string into list
    ansible.builtin.debug:
      msg: "Technologies are: {{ technologies | split(',') }}"    

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "tag map: {{ listTags | items2dict }}"  

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"  

  - name: convert yaml to json
    ansible.builtin.debug:
      ms: "json: {{ student_yaml | to_json }}"

  - name: save json to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"